### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by elstak** [google/google-authenticator-libpam#90]
Guys, it doesn't compile in RHEL7.4. I believe there's a bug only in that line 1876, where it should be like this instead:
 if (params.debug) {

---=

make  all-am
make[1]: Entering directory `/tmp/google-authenticator-libpam'
  CC       src/pam_google_authenticator_la-pam_google_authenticator.lo
src/pam_google_authenticator.c: In function 'google_authenticator':
src/pam_google_authenticator.c:1876:13: error: invalid type argument of '->' (have 'Params')
   if (params->debug) {
             ^
make[1]: *** [src/pam_google_authenticator_la-pam_google_authenticator.lo] Error 1
make[1]: Leaving directory `/tmp/google-authenticator-libpam'
make: *** [all] Error 2

**Comment by ThomasHabets** [comment]
Yeah, that was my bad. Fixed in https://github.com/google/google-authenticator-libpam/commit/f3fdab30b0521ee3ca10258ea76cfcef9171589b

Travis-CI still fails. Presumably because that environment uses an older PAM, but I've not looked deeper yet.

Keeping this open to make sure this is done right.
